

version: '3.9'

networks:
  dev_network:

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: netology

    networks:
      dev_network:
        aliases:
          - db-main

  app:
    build:
      context: .
    environment:
      PG_DSN: postgresql://app:1234@db-main:5432/netology
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      dev_network:
        aliases:
          - flask_api
    restart:
      always
    volumes:
      - ./app:/app
    working_dir: /app     
    entrypoint: sh ./run.sh  

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      API_URL: http://flask_api:5000
      PG_DSN: postgresql://app:1234@db-main:5432/netology
    depends_on:
      - db
      - app
    working_dir: /app
    entrypoint: pytest -v -s --disable-warnings

    networks:
      dev_network:
        aliases:
          - test_client
    volumes:
      - ./app/:/app
