FROM python:3.9

COPY . /app
COPY requirements.txt /app/requirements.txt
COPY requirements-dev.txt /app/requirements-dev.txt

WORKDIR /app

RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements-dev.txt

ENTRYPOINT pytest -v -s --disable-warnings